export const UPDATE_PAGE = 'UPDATE_PAGE'

export const UPDATE_HEADER_IMAGE = 'UPDATE_HEADER_IMAGE'

export const CHALLENGE_CONST = 'CHALLENGES'

export const CAUSE_CONST = 'CAUSE'

export const CREW_CONST  = 'CREW'

export const SPONSORSHIP_CONST = 'SPONSORSHIP'

export const SPONSORSHIP_SECOND_LEVEL_CONST = 'SPONSORSHIP_SECOND_LEVEL'

export const CONTACT_CONST = 'CONTACT'

export const HOMEPAGE_CONST = 'HOMEPAGE'

export const FOLLOW_US_CONST = 'FOLLOW_US'

export const SPONSORSHIP_CORPORATE_CONST = 'SPONSORSHIP_CORPORATE'
